services:
  isard-monitor-proxy:
    container_name: isard-monitor-proxy
    image: ${DOCKER_IMAGE_PREFIX}monitor-proxy:${DOCKER_IMAGE_TAG:-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.25
    ports:
      - published: ${HTTP_PORT:-80}
        target: ${HTTP_PORT:-80}
        mode: host
      - published: ${HTTPS_PORT:-443}
        target: ${HTTPS_PORT:-443}
        mode: host
    volumes:
      - /opt/isard/certs/acme:/etc/acme:rw
      - /opt/isard/certs/default:/certs:rw
      - /opt/isard-local/environment:/usr/local/etc/environment
      - /opt/isard-local/ipsec-fw/lists:/usr/local/etc/haproxy/lists
      - /opt/isard-local/haproxy/cfg:/usr/local/etc/haproxy/cfg/customs
      - /opt/isard-local/haproxy/spoe:/usr/local/etc/haproxy/spoe
    environment:
      FLAVOUR: ${FLAVOUR:-all-in-one}
      ENV: /usr/local/etc/environment
      FORBID_DOMAIN_IP: ${FORBID_DOMAIN_IP:-false}
      CORS: ${CORS:-*}
    env_file:
      - .env
