services:
  isard-tempo:
    container_name: isard-tempo
    image: grafana/tempo:2.5.0
    user: root
    volumes:
      - /opt/isard/stats/tempo:/data
      - ${BUILD_ROOT_PATH}/docker/tempo/config.yaml:/etc/tempo.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      isard-network:
        ipv4_address: ${DOCKER_NET:-172.31.255}.72
    restart: unless-stopped
    command: >-
      --config.file=/etc/tempo.yaml
    environment:
      DOMAIN:
      PROMETHEUS_ADDRESS: "${PROMETHEUS_ADDRESS:-http://isard-prometheus:9090}"
