version: '3.5'
services:
  isard-static:
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: docker/static/Dockerfile
      target: production
      args: 
        SRC_VERSION_ID: ${SRC_VERSION_ID}
        SRC_VERSION_LINK: ${SRC_VERSION_LINK}
