services:
  isard-vpn:
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: docker/vpn/Dockerfile
      target: production
      args:
        DOCKER_IMAGE_PREFIX: ${DOCKER_IMAGE_PREFIX}
        DOCKER_IMAGE_TAG: ${DOCKER_IMAGE_TAG}
